---
- name: Configure database {{ sonar_database_provider }}
  include: "configure-database-{{ sonar_database_provider }}.yml"
  when: sonar_configure_local_database

- name: Create user to run Sonar.
  user:
    name: "{{ sonar_username }}"
    shell: /bin/false
    create_home: true

- name: Download Sonar.
  get_url:
    url: "{{ sonar_download_url }}"
    dest: "{{ workspace }}/{{ sonar_version_directory }}.zip"
    validate_certs: "{{ sonar_download_validate_certs }}"

- name: Unzip Sonar.
  unarchive:
    src: "{{ workspace }}/{{ sonar_version_directory }}.zip"
    dest: /usr/local/
    copy: false
    creates: /usr/local/sonar/COPYING
    owner: "{{ sonar_username }}"
    group: "{{ sonar_group }}"

- name: Move Sonar into place.
  command: >
    mv /usr/local/{{ sonar_version_directory }} /usr/local/sonar
    creates=/usr/local/sonar/COPYING

- name: Configure sonar jdbc for {{ sonar_database_provider }}
  include: "configure-sonar-jdbc.yml"

- name: Symlink sonar bin.
  file:
    src: /usr/local/sonar/bin/linux-x86-64/sonar.sh
    dest: /usr/bin/sonar
    state: link
  register: sonar_symlink

- block:
    - name: Add sonar as init script for service management.
      file:
        src: /usr/local/sonar/bin/linux-x86-64/sonar.sh
        dest: /etc/init.d/sonar
        state: link

    - name: Ensure Sonar is running and set to start on boot.
      service:
        name: sonar
        state: started
        enabled: true
  when: "ansible_service_mgr != 'systemd'"

- block:
    - name: Copy SonarQube systemd unit file into place (for systemd systems).
      template:
        src: sonar.unit.j2
        dest: /etc/systemd/system/sonar.service
        owner: root
        group: root
        mode: 0755
      register: systemd_service

    - name: Copy SonarQube systemd unit file into place (for systemd systems).
      systemd:
        name: sonar
        daemon_reload: true
        enabled: true
        state: started
      when: systemd_service.changed

  when: "ansible_service_mgr == 'systemd'"

- name: Allow Sonar time to build on first start.
  pause: seconds=180
  when: sonar_symlink.changed
  tags: ['skip_ansible_lint']

- name: Make sure Sonar is responding on the configured port.
  wait_for: port=9000 delay=3 timeout=300
